repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks # Out-of-the-box hooks for pre-commit
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
        stages: [commit]
        # NB! Change the folder names you want to exclude if needed
        exclude: '^backend/(\w+/migrations)'
    -   id: check-ast
        stages: [commit]
    -   id: fix-byte-order-marker
        stages: [commit]
    -   id: check-json
        stages: [commit]
    -   id: check-merge-conflict
        stages: [commit]
    -   id: check-yaml
        stages: [commit]
    -   id: end-of-file-fixer
        stages: [commit]
        # NB! Change the folder names you want to exclude if needed
        exclude: '^(frontend/(build/|dist/))'
    -   id: debug-statements
        stages: [commit]
    -   id: no-commit-to-branch
        # NB! Change the branch names as needed
        args: [--branch, master, --branch, develop]
        stages: [commit]
    -   id: trailing-whitespace
        stages: [commit]
-   repo: https://github.com/jorisroovers/gitlint # Git commit message linter, check configs in .gitlint
    rev: v0.17.0
    hooks:
    -   id: gitlint
        stages: [commit-msg]
