repos:
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.10.0
    hooks:
    -   id: eslint
        args: [--ext, '.js', --ext, '.cjs', --ext, '.jsx', --rule, 'import/no-unresolved: 0', '--fix']
        additional_dependencies:
        -   eslint-config-airbnb-base@14.2.1
        -   eslint-config-airbnb@18.2.1
        -   eslint-plugin-mocha@8.0.0
        -   eslint-plugin-compat@3.11.1
        -   eslint-plugin-import@2.24.2
        -   eslint-plugin-jsx-a11y@6.4.1
        -   eslint-plugin-react-hooks@4.2.0
        -   eslint-plugin-react@7.25.1
        -   eslint@8.28.0
        stages: [commit]
        # NB! Change the folder names you want to exclude if needed
        exclude: '^(frontend/(build/|dist/|public/)|backend/.+/static/.*/vendor/)'
        types: [file]
        files: \.(js|jsx)$
