repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v6.8.0
    hooks:
      - id: eslint
        args: ["--rule", "import/no-unresolved: 0", "--fix"]
        additional_dependencies:
          - eslint-config-airbnb-base@14.2.1
          - eslint-config-prettier@6.15.0
          - eslint-import-resolver-alias@1.1.2
          - eslint-plugin-cypress@2.11.3
          - eslint-plugin-import@2.22.1
          - eslint-plugin-prettier@3.4.0
          - eslint-plugin-vue@6.2.2
          - eslint@6.8.0
          - prettier@1.19.1
        stages: [commit]
        types: [file]
        files: \.(js|vue)$
