repos:
-   repo: https://github.com/asottile/pyupgrade  # Upgrade syntax for newer versions of the language
    rev: v2.37.3
    hooks:
    -   id: pyupgrade
        args: [--py37-plus, --keep-runtime-typing]
        stages: [commit]
-   repo: https://github.com/ambv/black # Python code formatter
    rev: 22.6.0
    hooks:
    -   id: black
        stages: [commit]
        # NB! Change the folder names you want to exclude if needed
        exclude: '^backend/\w+/migrations'
-   repo: https://github.com/pycqa/isort # Sort imports
    rev: 5.10.1
    hooks:
    -   id: isort
        stages: [commit]
-   repo: https://github.com/pycqa/flake8 # Python/Django linter
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies:
        -   flake8-bugbear==22.7.1
        -   flake8-django==1.1.2
        -   flake8-isort==4.1.1
        -   flake8-pytest-style==1.6.0
        -   flake8-typing-imports==1.12.0
        stages: [commit]
        # NB! Change the folder names you want to exclude if needed
        exclude: '^backend/\w+/migrations'
-   repo: https://github.com/PyCQA/bandit # Security linter
    rev: 1.7.4
    hooks:
    -   id: bandit
        args: [-r, -n, '10', -x, '*/*/tests/*']
        stages: [commit]
        # NB! Change the folder names you want to exclude if needed
        exclude: '^backend/\w+/migrations'
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety # Check Python dependencies against safety-db
    rev: v1.3.0
    hooks:
    -   id: python-safety-dependencies-check
        files: ^backend/requirements/.*\.txt$
        stages: [commit]
-   repo: https://github.com/pre-commit/mirrors-mypy # Static type checker
    rev: v0.971
    hooks:
    -   id: mypy
        stages: [commit]
        files: '^backend/'
        # NB! Change the folder names you want to exclude if needed
        exclude: '^backend/\w+/migrations'
        additional_dependencies:
        - types-pytz==2022.1.2
        - types-bleach==5.0.3
        - types-python-dateutil==2.8.19
        - types-requests==2.28.7
